"""Python Linux x64 wheel 构建目标"""

import shutil
import sys
import tempfile
from pathlib import Path
from platform import system

from .cross import create_cross_wheel, ensure_zig_cmd, prepare_cpython_headers
from .utils import (
    RELEASE_DIR,
    REPO_ROOT,
    ensure_tool,
    file_size_str,
    get_version,
    log,
    run,
)


_LINUX_X64_PYCONFIG = """\
#ifndef Py_PYCONFIG_H
#define Py_PYCONFIG_H
/* Linux x86_64 - generated by builder for stable-ABI cross compilation. */
#define SIZEOF_VOID_P 8
#define SIZEOF_SIZE_T 8
#define SIZEOF_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_LONG_LONG 8
#define SIZEOF_SHORT 2
#define SIZEOF_DOUBLE 8
#define SIZEOF_FLOAT 4
#define SIZEOF_WCHAR_T 4
#define SIZEOF_FPOS_T 16
#define SIZEOF_OFF_T 8
#define SIZEOF_TIME_T 8
#define SIZEOF_PID_T 4
#define SIZEOF_UINTPTR_T 8
#define SIZEOF__BOOL 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_UNISTD_H 1
#define HAVE_WCHAR_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SSIZE_T 1
#define HAVE_DLFCN_H 1
#define HAVE_LONG_LONG 1
#define HAVE_UINTPTR_T 1
#define HAVE_INTTYPES_H 1
#define HAVE_SIGNAL_H 1
#define HAVE_ERRNO_H 1
#define HAVE_FCNTL_H 1
#define HAVE_MEMORY_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_DYNAMIC_LOADING 1
#define HAVE_GCC_UINT128_T 1
#define HAVE_STDARG_PROTOTYPES 1
#define WITH_PYMALLOC 1
#define DOUBLE_IS_LITTLE_ENDIAN_IEEE754_DOUBLE 1
#define PY_FORMAT_SIZE_T "z"
#define PY_FORMAT_LONG_LONG "ll"
#endif
"""


def _build_cross(auto_install: bool) -> None:
    """Cross-compile the stable-ABI extension when the host is not Linux."""
    zig_cmd = ensure_zig_cmd(auto_install)
    version = get_version()
    with tempfile.TemporaryDirectory(prefix="ts-cj-pylinux-") as tmp:
        work = Path(tmp)
        cpython = prepare_cpython_headers(work)
        pyconfig_dir = work / "pyconfig"
        pyconfig_dir.mkdir()
        (pyconfig_dir / "pyconfig.h").write_text(
            _LINUX_X64_PYCONFIG, encoding="utf-8"
        )
        so = work / "_binding.abi3.so"
        run([
            *zig_cmd, "cc", "-target", "x86_64-linux-gnu", "-shared", "-fPIC", "-O2",
            "-DPy_LIMITED_API=0x030A0000", "-DPY_SSIZE_T_CLEAN",
            "-DTREE_SITTER_HIDE_SYMBOLS", "-fvisibility=hidden",
            f"-I{pyconfig_dir}", f"-I{cpython / 'Include'}",
            f"-I{REPO_ROOT / 'src'}",
            str(REPO_ROOT / "bindings/python/tree_sitter_cangjie/binding.c"),
            str(REPO_ROOT / "src/parser.c"),
            str(REPO_ROOT / "src/scanner.c"),
            "-o", str(so),
        ])
        create_cross_wheel(
            so, "_binding.abi3.so", "linux_x86_64", version,
        )


def build(auto_install: bool = False) -> None:
    """
    【Python Linux x64 目标】构建 Linux x86_64 Python wheel

    构建原理：
    使用 setuptools 将 binding.c + parser.c + scanner.c 编译为 CPython C
    扩展（_binding.abi3.so）。通过稳定 ABI 机制（Py_LIMITED_API = 0x030A0000），
    生成的 wheel 兼容 Python 3.10+ 所有版本。构建流程：python3 -m build --wheel
    前端驱动 setuptools 后端，调用系统 C 编译器编译源码，将编译产物连同
    __init__.py、查询文件等打包为 .whl（zip 格式），标签为
    cp310-abi3-linux_x86_64。

    产物：release/tree_sitter_cangjie-{ver}-cp310-abi3-linux_x86_64.whl
    """
    log("构建 Python wheel（Linux x64）...")
    if system() != "Linux":
        _build_cross(auto_install)
        return

    ensure_tool("python3", hint="安装 Python 3.10+", auto_install=auto_install)
    run([sys.executable, "-m", "pip", "install", "--quiet",
         "build", "wheel", "setuptools"])
    py_dir = REPO_ROOT / "bindings" / "python"
    # 清理旧构建产物，避免残留文件干扰
    for name in ["dist", "build", "tree_sitter_cangjie.egg-info"]:
        d = py_dir / name
        if d.exists():
            shutil.rmtree(d)
    run([sys.executable, "-m", "build", "--wheel"], cwd=py_dir)
    wheels = list((py_dir / "dist").glob("*.whl"))
    if not wheels:
        log("Python wheel 未找到", "err")
        sys.exit(1)
    dest = RELEASE_DIR / wheels[0].name
    shutil.copy2(wheels[0], dest)
    log(f"Python wheel: {dest.name} ({file_size_str(dest)})", "ok")
